// <auto-generated />
using System;
using Aa_DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aa_DAL.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240807195024_create_db")]
    partial class create_db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aa_DAL.Models.HDCT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Gia")
                        .HasColumnType("bigint");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("HDCTs");
                });

            modelBuilder.Entity("Aa_DAL.Models.HinhThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenHinhThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HinhThucThanhToans");
                });

            modelBuilder.Entity("Aa_DAL.Models.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DienThoaiKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhachHangSoDienThoai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TongTien")
                        .HasColumnType("bigint");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("VoucherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangSoDienThoai");

                    b.HasIndex("NhanVienId");

                    b.HasIndex("VoucherId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("Aa_DAL.Models.KhachHang", b =>
                {
                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoDienThoai");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("Aa_DAL.Models.LichSuThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HinhThucThanhToanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SoTien")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HinhThucThanhToanId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("LichSuThanhToans");
                });

            modelBuilder.Entity("Aa_DAL.Models.Nhanvien", b =>
                {
                    b.Property<string>("TaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vaitro")
                        .HasColumnType("int");

                    b.HasKey("TaiKhoan");

                    b.ToTable("Nhanviens");
                });

            modelBuilder.Entity("Aa_DAL.Models.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Gia")
                        .HasColumnType("bigint");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("Aa_DAL.Models.Voucher", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<long>("PhanTramGiam")
                        .HasColumnType("bigint");

                    b.Property<string>("TenVoucher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Aa_DAL.Models.HDCT", b =>
                {
                    b.HasOne("Aa_DAL.Models.HoaDon", "HoaDon")
                        .WithMany("HDCTs")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aa_DAL.Models.SanPham", "SanPham")
                        .WithMany("HDCTs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Aa_DAL.Models.HoaDon", b =>
                {
                    b.HasOne("Aa_DAL.Models.KhachHang", null)
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangSoDienThoai");

                    b.HasOne("Aa_DAL.Models.Nhanvien", "Nhanvien")
                        .WithMany("HoaDons")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aa_DAL.Models.Voucher", "Voucher")
                        .WithMany("HoaDons")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nhanvien");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Aa_DAL.Models.LichSuThanhToan", b =>
                {
                    b.HasOne("Aa_DAL.Models.HinhThucThanhToan", "HinhThucThanhToanh")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("HinhThucThanhToanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aa_DAL.Models.HoaDon", "HoaDon")
                        .WithMany("LichSuThanhToans")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HinhThucThanhToanh");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Aa_DAL.Models.HinhThucThanhToan", b =>
                {
                    b.Navigation("LichSuThanhToans");
                });

            modelBuilder.Entity("Aa_DAL.Models.HoaDon", b =>
                {
                    b.Navigation("HDCTs");

                    b.Navigation("LichSuThanhToans");
                });

            modelBuilder.Entity("Aa_DAL.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Aa_DAL.Models.Nhanvien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Aa_DAL.Models.SanPham", b =>
                {
                    b.Navigation("HDCTs");
                });

            modelBuilder.Entity("Aa_DAL.Models.Voucher", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
